# Generated by Django 3.2.8 on 2021-10-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50, null=True)),
                ('empresa', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('prioridade', models.CharField(max_length=50)),
                ('servico', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'servico',
            },
        ),
    ]
